---
title: Centre National de Qualification Professionnelle
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  departements:
    title: departements
    output: true
    layout: departement
  partenaires:
    title: partenaires
    output: true
email: contact@cnqpsenegal.com
tel: 33 832 60 24
adresse: CNQP – Rocade Fann Bel-Air – Route de la SOSETRA
description: Le Centre National  de Qualification Professionnelle(CNQP) n’est pas
  une école dans le sens  classique du terme. Il a le statut d’Etablissement Public
  à Caractère Industriel et Commercial (EPIC) sous la tutelle du Ministère chargé
  de la Formation Professionnelle, de l’Apprentissage et de  l’Artisanat, est dirigé
  par un Conseil d’Administration tripartite (Etat – Employeurs – Travailleurs).
meta_description: Le Centre National  de Qualification Professionnelle(CNQP) n’est pas
  une école dans le sens  classique du terme. Il a le statut d’Etablissement Public
  à Caractère Industriel et Commercial (EPIC) sous la tutelle du Ministère chargé
  de la Formation Professionnelle, de l’Apprentissage et de  l’Artisanat, est dirigé
  par un Conseil d’Administration tripartite (Etat – Employeurs – Travailleurs).
baseurl: ''
url: ''
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
plugins:
- jekyll-feed
