# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Centre National de la Qualification Professionnelle
collections:
  filieres:
    title: Filieres
    output: true
email: contact@cnqp.com
tel: 33 832 60 24 - 33 832 39 79
adresse: 
description: >- # this means to ignore newlines until "baseurl:"
  Le Centre National  de Qualification Professionnelle(CNQP) n’est pas une école dans le sens 
  classique du terme. Il a le statut d’Etablissement Public à Caractère Industriel et Commercial (EPIC)
  sous la tutelle du Ministère chargé de la Formation Professionnelle, de l’Apprentissage et de 
  l’Artisanat, est dirigé par un Conseil d’Administration tripartite (Etat – Employeurs – Travailleurs).
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
