---
title: Centre National de la Qualification Professionnelle
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  departements:
    title: departements
    output: false
    hidden: false
email: contact@cnqp.com
tel: 33 832 60 24 - 33 832 39 79
adresse: 
description: Le Centre National  de Qualification Professionnelle(CNQP) n’est pas
  une école dans le sens  classique du terme. Il a le statut d’Etablissement Public
  à Caractère Industriel et Commercial (EPIC) sous la tutelle du Ministère chargé
  de la Formation Professionnelle, de l’Apprentissage et de  l’Artisanat, est dirigé
  par un Conseil d’Administration tripartite (Etat – Employeurs – Travailleurs).
baseurl: ''
url: ''
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
plugins:
- jekyll-feed
